### ISSUE TITLE
Can Tanuki be used to run an existing web project

### ISSUE THREAD

**Issue by elfgoh** [sausheong/tanuki#3]
Disclaimer: unsure I understood the concept of Tanuki correctly but here goes.

Say there is an existing web project in rails. As part of migration plan of the project to golang, os it possible to use Tanuki to run the rails project, and then add on new functionality in golang?

**Comment by sausheong** [comment]
Possibly, but with difficulty. You can use Tanuki to wrap around your existing web app and extend it accordingly but things like authentication and sessions will be an uphill struggle.
